name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly security scans on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    name: Security Vulnerability Scan
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: poetry install

    - name: Run pip-audit security scan
      run: poetry run pip-audit --format=json --output=security-report.json
      continue-on-error: true

    - name: Run pip-audit with sarif output for GitHub Security
      run: poetry run pip-audit --format=sarif --output=security-results.sarif || echo "No vulnerabilities found or SARIF generation failed"
      continue-on-error: true

    - name: Check if SARIF file exists
      id: sarif-check
      run: |
        if [ -f "security-results.sarif" ]; then
          echo "sarif-exists=true" >> $GITHUB_OUTPUT
        else
          echo "sarif-exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Upload SARIF results to GitHub Security
      uses: github/codeql-action/upload-sarif@v4
      if: steps.sarif-check.outputs.sarif-exists == 'true'
      with:
        sarif_file: security-results.sarif

    - name: Upload security report as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-report
        path: security-report.json

  codeql-analysis:
    name: CodeQL Security Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: python

    - name: Autobuild
      uses: github/codeql-action/autobuild@v4

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4